### ISSUE TITLE
Doesn't work on chrome

### ISSUE THREAD

**Issue by brij1234** [elliotwaite/thumbnail-rating-bar-for-youtube#12]
I'm running chrome 73.0.3683.75 on macOS. I did use the manual load unpacked bc of the [chrome store issue](https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/issues/9).
![Screen Shot 2019-03-15 at 10 50 24 PM](https://user-images.githubusercontent.com/9251787/54469871-ccd80b80-4774-11e9-9999-1b3159112849.png)

**Comment by mihirkumar** [comment]
I can confirm the same behavior on version 73.0.3683.75 on Windows 10. The extension needs some sort of update. @elliotwaite

**Comment by elliotwaite** [comment]
@brij1234 and @mihirkumar, thanks for reporting this. I just released the fix. You can try downloading the updated zip file.

This issue was related to new security measures that Chrome has just released. To conform with these new security requirements, I updated the extension to isolate all cross-origin ajax calls (the calls to the YouTube API) to a background script. Since background scripts do not run in the same render process as the web page the extension is being used on, this mitigates the threat of side-channel attacks (including Spectre). More info about Spectre and Chrome's new security measures can be found here:
https://www.chromium.org/Home/chromium-security/corb-for-developers
https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

**Comment by mihirkumar** [comment]
Thanks Elliot. Any idea when the extension will get verified on the Chrome store?

**Comment by elliotwaite** [comment]
I have resubmitted the updated app, but I do not know when I will hear from the Chrome store team again, they have very slow response times.
