### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Tenshi447** [elliotwaite/thumbnail-rating-bar-for-youtube#20]
Option to display rating bar **only** for videos with a specific (user-set) dislikes number. (or ratio, like 3likes:1dislikes) (and vice versa). This way we can have better control on using our quotas (not neccesarily getting rating info for **all** of the thumbnails loaded on current page).

Pardon me since I'm not a coder, this idea just popped up in mind XD My suggestion might also be wrong in some way.

**Comment by elliotwaite** [comment]
Even though this would limit the number of rating bars shown, it wouldn't reduce the amount of quota used since you'd still have to make the API call to figure out the likes ratio of the video. Are you getting close to running out of quota? I thought that the default allotted daily quota would be plenty.

**Comment by Tenshi447** [comment]
> Even though this would limit the number of rating bars shown, it wouldn't reduce the amount of quota used since you'd still have to make the API call to figure out the likes ratio of the video. Are you getting close to running out of quota? I thought that the default allotted daily quota would be plenty.

Ah, no. It was simply an idea I suddenly thought of haha. Thanks for clearing things up!
