### ISSUE TITLE
Feature doesn't work in Incognito mode

### ISSUE THREAD

**Issue by vargint** [elliotwaite/thumbnail-rating-bar-for-youtube#69]
The feature "Use the rating bar colors for the rating bar on the video page (when used with the [Return YouTube Dislike](https://returnyoutubedislike.com/) extension)."  doesn't work in incognito windows in Chrome.  It works in normal window. Everything else works great.

using "Version 98.0.4758.102 (Official Build) (64-bit)"

Thank you.

**Comment by elliotwaite** [comment]
I just tested this issue and it still works for me. Extensions are disabled by default in incognito mode. Did you make sure to change the settings that allow both of the extensions to work in incognito mode? Here's how: https://www.technipages.com/can-i-enable-extensions-in-incognito-mode-how

**Comment by vargint** [comment]
It's working now for me too.

In regular window I just needed to refresh the page to get it to work (once the settings were applied).  In incognito I needed to close all incognito tabs/windows for it to start working. (note, I only needed to refresh in incognito for the other settings to activate in this extension, this is the only setting that required a close+open) 

 Thank you!

**Comment by elliotwaite** [comment]
Okay, glad to hear you got it working. I'm not sure why the tab had to be closed and reopened to get it to work, but this is helpful to know about. And thanks for opening this issue as this info may also be helpful to others who run into this same issue.

I'm going to close this issue for now since the close-and-reopen workaround seems like a good enough solution for now, and it seems like this issue might be related to a rare edge case, but perhaps I'll look into this more in the future if this issue starts being reported more frequently. Thanks again for reporting it.
