### ISSUE TITLE
[Help] The progress bar and text says 0% when the creator disabled downvote

### ISSUE THREAD

**Issue by olivertzeng** [elliotwaite/thumbnail-rating-bar-for-youtube#83]
![截圖 2023-08-28 14 04 14](https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/assets/86348833/3bf51461-ccf6-45f3-908f-393285c5a8a2)
![截圖 2023-08-28 14 12 44](https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/assets/86348833/c8b41d90-26ca-41c9-9be4-6acacbb8fae5)

**Comment by elliotwaite** [comment]
Thanks for reporting this!

It looks like this issue is related to how Return YouTube Dislike works (and their API is what this extension uses to look up likes/dislikes data). According to [this issue](https://github.com/Anarios/return-youtube-dislike/issues/732), it looks like the "Disabled by Owner" message is shown when the video uploader has disabled the like count from being shown for the video (even though the message is shown on the dislike button, which I'm not sure why it is). And apparently, when Return YouTube Dislike doesn't have access to the like count for a video, it only records the number of dislikes, and the data returned for that video from the API will have 0 likes. For example, the data for the video in your screenshot is:
```
{
  "id": "_j33ek0q6ZU",
  "dateCreated": "2022-04-09T18:21:38.319419Z",
  "likes": 0,
  "dislikes": 290,
  "rating": 1,
  "viewCount": 3897480,
  "deleted": false
}
```

In that issue I linked above, the creator of Return YouTube Dislike mentioned:
> Yep, like @itsmetoolala said - it's not a bug, it's a feature. And it's not because I want to censor these videos - but because we lack data to show something comprehensible.
> 
> BUT. I do plan to show either raw dislike data from extension in these cases. OR to adjust total counts by view counts.

So if the "OR to adjust total counts by view counts" option is ever implemented (which I'm assuming means that they would adjust the number of likes by estimating it based on the dislikes and views), then that would resolve this issue. But that comment was from a long time ago and it still hasn't been added, so it probably won't be added any time soon.

Since there is no way to detect if a video has disabled its like count from the API data alone, I'm not sure how to resolve this issue other than potentially just hiding the "0%" for any videos that have 0 likes, but then that would also hide it for videos that legitimately have 0 likes. It seems like both cases are quite rare, case 1 being a video that has disabled the like count from being shown, and case 2 being a video that has 0 likes and >0 dislikes. So I'm not sure if it would be better to hide all occurrences of "0%" or not. What do you think about this option?

**Comment by olivertzeng** [comment]
oh ok so i think im okay with that lol

**Comment by olivertzeng** [comment]
thanks 4 your response

**Comment by elliotwaite** [comment]
By "okay with that" do you mean that you are okay with leaving it as is, or did you mean that you are okay with changing it so that it only shows a text percentage if there are more than 0 likes?

**Comment by olivertzeng** [comment]
A text percentage would be great(or an x) btw the text color should be grey instead of red

**Comment by elliotwaite** [comment]
Ah, so still show "0%", but if it has 0 likes, then don't colorize it, just keep it grey like the surrounding text?

**Comment by olivertzeng** [comment]
Yes, but only if the vote system is enabled

**Comment by elliotwaite** [comment]
From the data returned by the API, I can't tell if the vote system is enabled, I can only tell if it has 0 likes, which will be the case if the vote system is disabled, but will also be the case if the vote system is enabled but no one has liked it yet. So I would have to make the change apply to both cases.

**Comment by olivertzeng** [comment]
If it's disabled set the bar to grey(I've changed the bar color so maybe after you've changed this setting set the default color to something that's not grey and tell people not to set the color to grey)and show a Red Cross ❌ next to the video title

**Comment by olivertzeng** [comment]
> From the data returned by the API, I can't tell if the vote system is enabled, I can only tell if it has 0 likes, which will be the case if the vote system is disabled, but will also be the case if the vote system is enabled but no one has liked it yet. So I would have to make the change apply to both cases.

Oh that sounds bad. So if both votes are 0 set the whole bar to grey and the text to grey too. But I think show the text to 50% to let people know that no one has vote it yet

**Comment by elliotwaite** [comment]
Ah, currently if there are no votes, it just doesn't add the percentage at all. I feel like a grey 50% might be confusing.

About the 0 likes thing, another option would be to only make it grey if it has 0 dislikes and >= 50 likes, since that would probably indicate that the rating system has been disabled for that video.

**Comment by olivertzeng** [comment]
> Or maybe instead of making the percentage grey when it has 0 likes and 10+ dislikes, it should just not be shown at all, similar to how the 0 ratings case is currently handled. What do you think?

I was thinking of that and that's a great idea! Since it's disabled then we'd rather don't show them

**Comment by elliotwaite** [comment]
Okay, that sounds good to me. Do you think 10+ dislikes is a good number for the threshold of when it will switch to not showing it if it still has 0 likes?

**Comment by olivertzeng** [comment]
> Okay, that sounds good to me. Do you think 10+ dislikes is a good number for the threshold of when it will switch to not showing it if it still has 0 likes?

I think I'm unable to downvote when the vote system is disabled too

**Comment by olivertzeng** [comment]
If downvoting is active when voting is disabled, I think 10 is fine

**Comment by olivertzeng** [comment]
Oh I see![image](https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/assets/86348833/3fa029b5-6f9a-48c4-90c9-bcff3897ea91)

**Comment by olivertzeng** [comment]
I can downvote!

**Comment by elliotwaite** [comment]
Yeah, I think you can still upvote and downvote even when it's disabled, but neither of the counts are shown on the video page, and Return YouTube dislike only tracks the downvotes.

... And maybe before it reaches that threshold it could show the 0% as grey, since it is uncertain if it is due to the rating system being disabled.

**Comment by elliotwaite** [comment]
So I've updated the extension (but haven't submitted it yet) to use these settings:
* If the video has 0 likes and < 10 dislikes, it shows a grey 0%.
* If the video has 0 likes and >= 10 dislikes, it doesn't show the percentage at all.

Does that sound good to you?

**Comment by olivertzeng** [comment]
> So I've updated the extension (but haven't submitted it yet) to use these settings:
> 
> * If the video has 0 likes and < 10 dislikes, it shows a grey 0%.
> 
> * If the video has 0 likes and >= 10 dislikes, it doesn't show the percentage at all.
> 
> 
> 
> Does that sound good to you?

That sounds like a good idea! BTW can I translate this extension

**Comment by olivertzeng** [comment]
Yeah btw keep in mind that if 10 people has downvoted with 0 likes it will be judged as disabled but if someone undownvoted the video will this still count as disabled too

**Comment by elliotwaite** [comment]
Yep, that can happen, but I think that's a tradeoff that I'm okay with for now.

I've submitted the new version for review (version 1.8.14). It should be available as an update once it's been approved, which usually happens within an hour for Firefox, within 24 hours for Chrome, and within a week for Edge.

I'm going to close this issue for now, but feel free to continue this conversation if you think the update could be improved further in some way or if the updated version is working as expected.

Thanks again for opening this issue.

**Comment by olivertzeng** [comment]
> Yep, that can happen, but I think that's a tradeoff that I'm okay with for now.
> 
> 
> 
> I've submitted the new version for review (version 1.8.14). It should be available as an update once it's been approved, which usually happens within an hour for Firefox, within 24 hours for Chrome, and within a week for Edge.
> 
> 
> 
> I'm going to close this issue for now, but feel free to continue this conversation if you think the update could be improved further in some way or if the updated version is working as expected.
> 
> 
> 
> Thanks again for opening this issue.

Wow that's cool I never know the time they approve these extensions until now!

**Comment by elliotwaite** [comment]
Yeah, for simple updates, those are rough estimates based on my experience. However, if I ever change the set of permissions that the extension requires, the reviews usually take longer.

**Comment by olivertzeng** [comment]
oh ok
