### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#86]
Can you fetch thumbnail rating for Youtube shorts video as well?

**Comment by elliotwaite** [comment]
Thanks for the feature request! I just updated the code to support Shorts. I've submitted the updated version (v1.8.15) to the browser extension stores. It's already available for Firefox and should be available for Chrome within 24 hrs and on Edge within a week (they have a slow review process).

I've only tested it out a little bit, so let me know if you notice any places where Shorts still aren't getting rating bars added to them.

**Comment by elliotwaite** [comment]
You should be able to apply the same changes here:
https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/blob/master/extension/content-script.js#L192

**Comment by shivamkumarc** [comment]
Oh thank you it`s working, actually the changed function was this:

function getRatingPercentageHtml(videoData) {
  let r = (1 - videoData.rating) * 1275
  let g = videoData.rating * 637.5 - 255
  if (!isDarkTheme) {
    g = Math.min(g, 255) * 0.85
  }
  let rgb = 'rgb(' + r + ',' + g + ',0)'
  let text = videoData.likes.toLocaleString() + ' likes, ' +
videoData.dislikes.toLocaleString() + ' dislikes'

  return '<span class="style-scope ytd-video-meta-block
ytrb-percentage" style="color:' +
      rgb + ' !important">' + text + '</span>'
}


Thank you so much for adding thumbnail rating for Shorts video as well

**Comment by elliotwaite** [comment]
Ah, okay, got it.

No problem. Thanks for the suggestion.

**Comment by shivamkumarc** [comment]
I think after adding thumbnail rating for shorts video loading of the thumbnail rating bar has become slow

**Comment by elliotwaite** [comment]
This could be true. The only difference between the previous version and the current version should be the additional requests made to the API for the Shorts' ratings. This would make it more likely that you hit the API's rate limit sooner, however, I would think that this would not be very noticeable.

**Comment by elliotwaite** [comment]
It does seem to be slower. Maybe I can make it so it delays adding ratings for shorts so that it prioritizes non-shorts first.

To download any old version of the repo:
1. Go to the [repo's Code section](https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube).
2. Click the "commits" link near the top right of the file browser viewer.
3. For whichever commit you want to view, click the "< >" button at the right side of that commit to view the repo after that commit.
4. Click the green "< > Code" button and choose "Download ZIP".
5. You can then extract the contents of that Zip file and load the contained "extension" directory as an unpacked extension.

**Comment by shivamkumarc** [comment]
Thank you,done it
