### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by shivamkumarc** [elliotwaite/thumbnail-rating-bar-for-youtube#87]
The extension is not able to fetch thumbnail rating for the video which has "The following content may contain graphic or violent imagery Viewer discretion is advised".Any fix for this?
Sample YouTube video link:https://www.youtube.com/watch?v=Y1d2iyPMoWo&t=1s
![Screenshot (110)](https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/assets/96905752/77b49d51-9082-4e80-a04a-79a81f3455c3)
![Screenshot (111)](https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube/assets/96905752/47a045d2-8dc5-4e31-8f04-e4b90da4e09b)

**Comment by elliotwaite** [comment]
Thanks for reporting this. This seems to be an issue with the Return YouTube Dislike API. The returned data for this video has 0 likes and 0 dislikes:
```
{
  "id": "Y1d2iyPMoWo",
  "dateCreated": "2023-11-18T14:29:10.958776Z",
  "likes": 0,
  "dislikes": 0,
  "rating": 0,
  "viewCount": 2986280,
  "deleted": false
}
```
To test out their API:
1. Go [here](https://returnyoutubedislikeapi.com/swagger/index.html).
2. Expand the `/Votes` endpoint.
3. Click the "Try it out" button in the top right of the expanded section.
4. Enter the video's ID (`Y1d2iyPMoWo`) into the `videoID` field.
5. Click the "Execute" button.

If you want to pursue this issue further, you could open an issue about this on [their GitHub repo](https://github.com/Anarios/return-youtube-dislike).

I'm going to close this issue for now, since it seems to be an issue with the external API, but feel free to update this issue if you have any additional info about this.

**Comment by shivamkumarc** [comment]
Yeah,i see the problem with Return yourn dislike
